# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171114_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 13, 3, 57, 498922)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 13, 3, 57, 498942)),
        ),
    ]
