# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171120_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 18, 16, 35, 776691)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 18, 16, 35, 776721)),
        ),
    ]
