# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20171121_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 11, 50, 37, 542529)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 11, 50, 37, 542549)),
        ),
    ]
